name: project4_remidi
description: A new Flutter project.

# Versi aplikasi
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Pastikan versi SDK sesuai dengan Flutter Anda

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Ikon bawaan Flutter
  google_fonts: ^6.1.0     # Tambahkan untuk mendukung GoogleFonts
  intl: ^0.18.0           # Untuk format internasional, perbarui jika perlu

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0    # Aturan linting untuk kode yang lebih bersih

# Konfigurasi Flutter
flutter:
  uses-material-design: true

  # Tambahkan aset atau font jika diperlukan
  assets:
    - assets/  # Contoh direktori aset, sesuaikan dengan kebutuhan

  # Font (opsional, jika Anda ingin menambahkan font lokal)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf