name: project4_remidi
description: A new Flutter project for student registration.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0  # Pastikan versi terbaru
  supabase_flutter: ^2.5.0  # Periksa update di pub.dev
  flutter_typeahead: ^5.2.0  # Periksa update
  connectivity_plus: ^6.0.3  # Periksa update
  intl: ^0.20.2  # Pastikan versi terbaru
  # provider: ^6.0.0  # Opsional: untuk state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # logger: ^2.0.0  # Aktifkan jika ingin logging terstruktur

flutter:
  uses-material-design: true
  assets:
    - assets/images/  # Tambahkan jika ada aset gambar