name: project4_remidi
description: A new Flutter project for student registration.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0  # Pastikan menggunakan versi terbaru yang stabil

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Opsional: Untuk linter yang lebih ketat

flutter:
  uses-material-design: true